// Outfit Web-App – Kleiderschrank-Fundus
// Einfach am Mac anpassbar: Teile ergänzen, ändern oder active:false setzen.
// Kategorien: Hose, Tshirt, Longsleeve, Hemd, Pullover, Overshirt, Blazer, Cardigan, Jacke, Weste, Schuhe, Kappe, Mütze, Schal, Uhr
window.WARDROBE = [
  {name:'schwarze Stoffhose', category:'Hose', color:'schwarz', warmth:'mittel', formality:'casual', fit:'weites Bein', material:'Canvas', active:true},
  {name:'grauer Pullover', category:'Pullover', color:'grau', warmth:'warm', formality:'casual', fit:'weit', material:'Sweatstoff', active:true},
  {name:'schwarzer Pullover', category:'Pullover', color:'schwarz', warmth:'warm', formality:'casual', fit:'weit', material:'Sweatstoff', active:true},
  {name:'blauer Strickkapuzenpullover', category:'Pullover', color:'dunkelblau', warmth:'warm', formality:'casual', fit:'weit', material:'Kaschmir-Strick', active:true, notes:'nur Winter/kalter Herbst bevorzugt'},
  {name:'hellblaues Longsleeve', category:'Longsleeve', color:'eisblau', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'dunkelblaues Longsleeve', category:'Longsleeve', color:'dunkelblau', warmth:'leicht', formality:'casual', fit:'regular', material:'Baumwolle', active:true},
  {name:'waldgrünes T-Shirt', category:'Tshirt', color:'dunkles waldgrün', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'polar blue T-Shirt', category:'Tshirt', color:'ice blau', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'lava graues T-Shirt', category:'Tshirt', color:'lava grau', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'schwarzes T-Shirt', category:'Tshirt', color:'schwarz', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'pinkes T-Shirt', category:'Tshirt', color:'pastell beere', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'gelbes T-Shirt', category:'Tshirt', color:'pastell gelb', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'olivegrünes T-Shirt', category:'Tshirt', color:'olivegrün', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'weißes T-Shirt', category:'Tshirt', color:'weiß', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'bordeauxrotes T-Shirt', category:'Tshirt', color:'bordeauxrot', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'graublaues T-Shirt', category:'Tshirt', color:'graublau', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'navy T-Shirt', category:'Tshirt', color:'navy', warmth:'mittel', formality:'casual', fit:'weit', material:'Baumwolle', active:true},
  {name:'Jeans', category:'Hose', color:'jeansblau', warmth:'warm', formality:'casual', fit:'weit', material:'Jeans', active:true},
  {name:'beige Stoffhose', category:'Hose', color:'beige', warmth:'leicht', formality:'casual', fit:'weites Bein', material:'-', active:true},
  {name:'grüne Stoffhose', category:'Hose', color:'olivegrün', warmth:'leicht', formality:'casual', fit:'weites Bein', material:'-', active:true},
  {name:'grüne Corthose', category:'Hose', color:'grüngrau', warmth:'warm', formality:'casual', fit:'weit', material:'Cord', active:true},
  {name:'off-white/pinke Batikjeans', category:'Hose', color:'off-white beige mit pinkem Batikmuster', warmth:'mittel', formality:'casual', fit:'weit', material:'Jeans', active:true},
  {name:'blaue Leinenhose', category:'Hose', color:'navy', warmth:'leicht', formality:'casual', fit:'weit', material:'Leinen', active:true},
  {name:'blaue Stoffhose', category:'Hose', color:'navy', warmth:'leicht', formality:'casual', fit:'weit', material:'-', active:true, avoidFor:'Termin'},
  {name:'hellblaues Hemd mit Streifen', category:'Hemd', color:'hellblau mit feinen hellrot/grünen Streifen', warmth:'leicht', formality:'business', fit:'regular', material:'-', active:true},
  {name:'weißes Hemd', category:'Hemd', color:'weiß', warmth:'leicht', formality:'business', fit:'regular', material:'-', active:true},
  {name:'blau weiß gestreiftes Hemd', category:'Hemd', color:'royalblau/weiß', warmth:'mittel', formality:'casual', fit:'regular', material:'-', active:true},
  {name:'Carhartt Hemd', category:'Hemd', color:'grau weiß', warmth:'mittel', formality:'casual', fit:'regular', material:'fest', active:true},
  {name:'hellblaues Hemd', category:'Hemd', color:'hellblau', warmth:'leicht', formality:'casual', fit:'weit', material:'-', active:true},
  {name:'hellblaues kurzes Leinenhemd', category:'Hemd', color:'hellblau', warmth:'leicht', formality:'casual', fit:'weit', material:'Leinen', active:true},
  {name:'blaues Hemd', category:'Hemd', color:'navy', warmth:'mittel', formality:'casual', fit:'regular', material:'-', active:true},
  {name:'kariertes Flanellhemd', category:'Hemd', color:'olivegrün/gelb', warmth:'warm', formality:'casual', fit:'oversized', material:'-', active:true},
  {name:'französische Arbeitsjacke', category:'Overshirt', color:'knallblau', warmth:'mittel', formality:'casual', fit:'weit', material:'Jeans', active:true},
  {name:'Cargojacke', category:'Overshirt', color:'navy', warmth:'mittel', formality:'casual', fit:'weit', material:'-', active:true},
  {name:'brauner Wollblazer', category:'Blazer', color:'braun', warmth:'warm', formality:'casual', fit:'oversized', material:'Wolle', active:true},
  {name:'blaue Wollwalkjacke', category:'Cardigan', color:'navy', warmth:'warm', formality:'casual', fit:'weit', material:'Wolle', active:true},
  {name:'hellblaues Wollhemd', category:'Hemd', color:'hellblau', warmth:'warm', formality:'casual', fit:'regular', material:'-', active:true},
  {name:'petrol Cordhemd', category:'Hemd', color:'petrol', warmth:'warm', formality:'casual', fit:'regular', material:'Cord', active:true},
  {name:'helle Leinenjacke', category:'Overshirt', color:'naturleinen', warmth:'leicht', formality:'casual', fit:'regular', material:'Leinen', active:true},
  {name:'Wildlederjacke', category:'Jacke', color:'caramel', warmth:'mittel', formality:'casual', fit:'weit', material:'Leder', active:true},
  {name:'schwarze Daunenjacke', category:'Jacke', color:'schwarz', warmth:'warm', formality:'casual', fit:'regular', material:'-', active:true},
  {name:'schwarze Regenjacke', category:'Jacke', color:'schwarz', warmth:'leicht', formality:'casual', fit:'slimfit', material:'-', active:true},
  {name:'schwarze Steppweste', category:'Weste', color:'schwarz', warmth:'warm', formality:'casual', fit:'regular', material:'-', active:true},
  {name:'dunkelblaue Stoffsommerjacke', category:'Jacke', color:'dunkelblau', warmth:'leicht', formality:'casual', fit:'regular', material:'Baumwolle', active:true, notes:'nur draußen'},
  {name:'Lederschuhe', category:'Schuhe', color:'caramel', warmth:'-', formality:'casual', fit:'-', material:'Leder', active:true},
  {name:'weiße Sneaker', category:'Schuhe', color:'weiß', warmth:'-', formality:'casual', fit:'-', material:'Leder', active:true},
  {name:'dunkelgrüne Sneaker', category:'Schuhe', color:'dunkelgrün', warmth:'-', formality:'casual', fit:'-', material:'Stoff', active:true},
  {name:'helle hohe Sneaker', category:'Schuhe', color:'hellgrau mit neongelb', warmth:'-', formality:'casual', fit:'-', material:'-', active:true},
  {name:'schwarze Adidas Gazelle', category:'Schuhe', color:'schwarz', warmth:'-', formality:'casual', fit:'-', material:'-', active:true},
  {name:'schwarze Kappe', category:'Kappe', color:'schwarz', warmth:'leicht', formality:'casual', fit:'-', material:'-', active:true},
  {name:'grüne Kappe', category:'Kappe', color:'grüngrau', warmth:'leicht', formality:'casual', fit:'-', material:'-', active:true},
  {name:'grüne Wollmütze', category:'Mütze', color:'grün', warmth:'warm', formality:'casual', fit:'-', material:'-', active:true},
  {name:'graurote Wollmütze', category:'Mütze', color:'grau mit rot', warmth:'warm', formality:'casual', fit:'-', material:'-', active:true},
  {name:'Uhr silber schwarzes Band', category:'Uhr', color:'schwarz', warmth:'-', formality:'-', fit:'-', material:'-', active:true},
  {name:'Uhr silber/gold blaues Band', category:'Uhr', color:'blau', warmth:'-', formality:'-', fit:'-', material:'-', active:true},
  {name:'hellgrauer Schal', category:'Schal', color:'hellgrau', warmth:'warm', formality:'casual', fit:'-', material:'Wolle', active:true},
  {name:'dunkelblauer Schal', category:'Schal', color:'dunkelblau', warmth:'warm', formality:'casual', fit:'-', material:'Wolle', active:true},
  {name:'dunkelblauer Sofiskarf', category:'Schal', color:'dunkelblau', warmth:'mittel', formality:'casual', fit:'-', material:'Wolle', active:true}
];
